# Generated by Django 3.2 on 2021-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_it_latest_post_it_post_it_recent_post_it_trending_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_latest_post',
            name='img',
            field=models.ImageField(upload_to='it_pics'),
        ),
        migrations.AlterField(
            model_name='it_post',
            name='img',
            field=models.ImageField(upload_to='it_pics'),
        ),
        migrations.AlterField(
            model_name='it_recent_post',
            name='img',
            field=models.ImageField(upload_to='it_pics'),
        ),
        migrations.AlterField(
            model_name='it_trending_post',
            name='img',
            field=models.ImageField(upload_to='it_pics'),
        ),
    ]
