# Generated by Django 3.2 on 2021-06-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_business_latest_post_business_post_business_recent_post_business_trending_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_latest_post',
            name='img',
            field=models.ImageField(upload_to='business_pics'),
        ),
        migrations.AlterField(
            model_name='business_post',
            name='img',
            field=models.ImageField(upload_to='business_pics'),
        ),
        migrations.AlterField(
            model_name='business_recent_post',
            name='img',
            field=models.ImageField(upload_to='business_pics'),
        ),
        migrations.AlterField(
            model_name='business_trending_post',
            name='img',
            field=models.ImageField(upload_to='business_pics'),
        ),
    ]
