# Generated by Django 3.2 on 2021-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_sport_latest_post_sport_post_sport_recent_post_sport_trending_post_travel_latest_post_travel_post_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
    ]
