# Generated by Django 3.2 on 2021-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210611_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport_post',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='sport_pics'),
        ),
        migrations.AlterField(
            model_name='travel_post',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='travel_pics'),
        ),
    ]
