# Generated by Django 3.2 on 2021-06-15 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0016_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_post',
            name='likes',
            field=models.ManyToManyField(related_name='business_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='it_post',
            name='likes',
            field=models.ManyToManyField(related_name='it_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sport_post',
            name='likes',
            field=models.ManyToManyField(related_name='sport_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travel_post',
            name='likes',
            field=models.ManyToManyField(related_name='travel_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
